version: '3.8'
services:
  ubase:
    build:
      context: .
      dockerfile: ./Dockerfile
      # args:
      #   - docker_user=${docker_user}
        # - UID=${UID}
        # - GID=${GID}
    # user: ${docker_user}
    image: ubase
    container_name: ubase
    tty: true
    # restart: always
    # ports:
    #   - 80:80
    #   - 443:443
    environment:
      - TZ=Asia/Tokyo
      - DISPLAY
      - XMODIFIERS # X用のIM設定
      - GTK_IM_MODULE # GTK(GimpToolKit)用のIM設定
      - QT_IM_MODULE # QT用のIM設定
      # [Dockerコンテナ上のGUIアプリで日本語入力する（Linux）](https://zenn.dev/ysuito/articles/c196ae84c95e31)
      - DefalutIMModule=fcitx
      - DBUS_SESSION_BUS_ADDRESS
    volumes:
      - /run/user/${UID:-1000}/bus:/run/user/${UID:-1000}/bus
    #   - ./server/nginx/conf.d/app.dev.conf:/etc/nginx/conf.d/default.conf
    #   - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./server/nginx/proxy.conf:/etc/nginx/proxy.conf
    #   - ./server/nginx/mime.types:/etc/nginx/conf/mime.types
    #   - ./data/work:/usr/share/nginx/html/resource
    # links:
    #   - app
    # depends_on:
    #   - app
